version: "3.7"
services:
  web:
    build:
      context: .
      target: web
    command: cargo run
    ports: 
      - "8080:8080"
    env_file: .env
    depends_on:
      - postgres
    links:
      - postgres
    volumes:
      - .:/usr/web/app/

  migrate-up:
    build:
      context: .
      target: migration
    command: diesel migration run
    env_file: .env
    depends_on:
      - postgres
    links:
      - postgres
    volumes:
      - .:/usr/web/app/

  postgres:
    image: postgres:9.6-alpine
    ports:
      - 5432
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rust"]
      interval: 10s
      timeout: 5s
      retries: 5
    
